<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Student;
use App\Models\StudentAddress;
use App\Models\ParentInfo;
use App\Models\Classes;
use App\Models\SchoolYear;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\DB;

class StudentSeeder extends Seeder
{
    public function run(): void
    {
        $schoolYear = SchoolYear::where('school_year', '2024-2025')->firstOrFail();

        $gradeLevels = [
            'kindergarten',
            // 'grade1',
            // 'grade2',
            // 'grade3',
            // 'grade4',
            // 'grade5',
            // 'grade6'
        ];

        $classes = [];
        foreach ($gradeLevels as $level) {
            $classes[$level] = Classes::firstOrCreate([
                'grade_level' => $level,
                'section' => 'A',
            ]);
        }

        $baseLRN = 112828080000; // base LRN for autogenerated students

        foreach ($gradeLevels as $gradeIndex => $gradeLevel) {
            for ($i = 0; $i < 30; $i++) {
                $isMale = $i < 15;
                $firstNames = $isMale
                    ? ['Liam', 'Noah', 'James', 'Lucas', 'Benjamin', 'Elijah', 'Logan', 'Mason', 'Ethan', 'Alexander', 'Daniel', 'Matthew', 'Jacob', 'Michael', 'William']
                    : ['Emma', 'Olivia', 'Ava', 'Isabella', 'Sophia', 'Charlotte', 'Amelia', 'Mia', 'Harper', 'Evelyn', 'Abigail', 'Ella', 'Elizabeth', 'Camila', 'Luna'];

                $lastNames = ['Garcia', 'Santos', 'Reyes', 'Cruz', 'Torres', 'Lopez', 'Dela Cruz', 'Gomez', 'Domingo', 'Morales', 'Navarro', 'Castillo', 'Ramos', 'Mendoza', 'Flores'];

                $lrn = (string) ($baseLRN + ($gradeIndex * 100) + $i);

                $address = StudentAddress::create([
                    'house_no' => rand(100, 999),
                    'street_name' => 'Main St',
                    'barangay' => 'Barangay Uno',
                    'municipality_city' => 'Sample City',
                    'province' => 'Sample Province',
                    'zip_code' => '1000',
                    'country' => 'Philippines',
                    'pob' => 'Sample City',
                ]);

                $parent = ParentInfo::create([
                    'father_fName' => 'Juan',
                    'father_mName' => 'Dela',
                    'father_lName' => 'Cruz',
                    'father_phone' => '0917' . rand(1000000, 9999999),
                    'mother_fName' => 'Maria',
                    'mother_mName' => 'Santos',
                    'mother_lName' => 'Reyes',
                    'mother_phone' => '0918' . rand(1000000, 9999999),
                    'emergcont_fName' => 'Pedro',
                    'emergcont_mName' => 'Lopez',
                    'emergcont_lName' => 'Gomez',
                    'emergcont_phone' => '0920' . rand(1000000, 9999999),
                ]);

                $student = Student::create([
                    'student_lrn' => $lrn,
                    'student_fName' => $firstNames[$i % 15],
                    'student_mName' => 'M.', // Static middle name for demo
                    'student_lName' => $lastNames[$i % 15],
                    'student_extName' => null,
                    'student_dob' => now()->subYears(5 + $gradeIndex)->format('Y-m-d'),
                    'student_sex' => $isMale ? 'male' : 'female',
                    'student_photo' => null,
                    'qr_code' => Str::uuid(),
                    'address_id' => $address->id,
                    'parent_id' => $parent->id,
                ]);

                DB::table('class_student')->insert([
                    'student_id' => $student->id,
                    'class_id' => $classes[$gradeLevel]->id,
                    'school_year_id' => $schoolYear->id,
                ]);
            }
        }
    }
}
